#!/bin/bash
#
#$ -S /bin/bash
#$ -o /netapp/home/vanben/lunus_processing/blga05/COMBAT
#$ -e /netapp/home/vanben/lunus_processing/blga05/COMBAT
#$ -cwd
#$ -l mem_free=2G
#$ -pe smp 8
#$ -R yes
#$ -l arch=linux-x64
#$ -l h_rt=48:00:00

source /netapp/home/vanben/programs/phenix-dev-1839/phenix_env.sh
source /netapp/home/vanben/ccp4/ccp4-6.3.0/bin/ccp4.setup-sh
export PATH=/netapp/home/vanben/programs/XDS-INTEL64_Linux_x86_64:$PATH
export KMP_STACKSIZE=8m
export IPMOSFLM=/netapp/home/vanben/mosflm
export XIA2_ROOT=/netapp/home/vanben/xia2/xia2-0.3.6.3
source $XIA2_ROOT/setup.sh

libtbx.configure xfel


libtbx.python combat.py combat.params
